### ISSUE TITLE
Incorrect double concat filter

### ISSUE THREAD

**Issue by danieldeutsch** [jweese/thrax2#1]
The filter doesn't remove `[NN+IN+NNP]`.

https://github.com/jweese/thrax2/blob/a6c5f2d12bcb29a426e184e654b93fbce368b5a5/scripts/filter_double_concat#L5

`print unless grep /\[\S*?\+\S*?\+\S*?\]/, $_;` works, but I don't know perl well enough to know if there's something more efficient.

**Comment by jweese** [comment]
Aha, I think this was back when I thought `/blah/g` in list context returns the list of matches. But I think it doesn't. I've had problems with that before. Your solution should work, though, but it can be simplified to

`print unless /your regex/;`

**Comment by danieldeutsch** [comment]
This is actually wrong because it won't match `[NNP+IN+DT,2]`

**Comment by danieldeutsch** [comment]
Never mind, it does

**Comment by jweese** [comment]
what a rollercoaster
